CHUNK_SIZE = 1000
CHUNK_OVERLAP = 200

TOP_K = 5
DEFAULT_TOP_K = 30
RERANK_TOP_K = 10
MIN_RELEVANCE_SCORE = 1.5
FINAL_CONTEXT_K = 5

EMBEDDING_MODEL = "BAAI/bge-small-en-v1.5"

COLLECTION_NAME = "documents"

